# Generated by Django 3.2.7 on 2023-03-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_dm_ime_pd_se'),
    ]

    operations = [
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Files')),
                ('desc', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Files')),
                ('desc', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Files')),
                ('desc', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
